name = "assetmantle-docs"
type = "webpack"
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./site",entry-point = "workers-site"}
compatibility_date = "2021-12-20"
zone_id = '4d52f36b396dad8cddd83b3d5e0fbda4'

[env.release]
route = 'https://docs.assetmantle.one/*'
