name: Website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Documentation
        run: |
          mkdocs build -v
      - name: archive build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip site
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: build.zip

  deploy:
    # The type of runner that the job will run on
    needs: build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@v2
        with:
          name: web
      - name: Deploy
        uses: alinz/ssh-scp-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE}}
          port: 22
          ssh_before: |
            rm -r build.zip
          # then uploads these 2 files
          scp: |
            build.zip ${{ secrets.USER }}@${{ secrets.HOST }}:~/build.zip
          # then run these commands
          ssh_after: |
            ${{ secrets.SCRIPT_PATH }}
